---
- hosts: all
  ansible_user: ubuntu
  become: True
  tasks:
   - name: Install aws cli
     apt:
      name: awscli
      state: present
   - name: Install docker-compose
     get_url:
      url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
...
